### ISSUE TITLE
Exclamation mark in brackets

### ISSUE THREAD

**Issue by ersten** [vanderlee/php-sentence#1]
Hello! First of all, I would like to say thank you for this wonderful tool! Its really powerful and silmply utility. And works perfectly with Russian language.

But, I noticed one feature: text
`You are both kind, considerate, full of life (even witty!). What more could we both want?`
will splitted to the two sentences:
1.`You are both kind, considerate, full of life (even witty!`
2.`). What more could we both want?`

Maybe its not normal punctuation, but this feature a little similar to bug. :)

Unfortunately, I am not an experienced PHP-developer, and I can't offer a solution to this issue.

Thanks!

**Comment by vanderlee** [comment]
Thanks for the feedback!

As stated in the documentation, the exact position of splitting may be wrong in certain situations, but the sentence count is still good.

That having been said, I don't think I have a testcase for the particular structure you used, so I may be able to fit is. No guarentees though.

**Comment by vanderlee** [comment]
I think this fixes the issue.
Please test.

**Comment by ersten** [comment]
Thank you very much! This works perfectly!
