### ISSUE TITLE
Wrong parsing at numbers with dot.

### ISSUE THREAD

**Issue by ulziibadrakh-p** [vanderlee/php-sentence#14]
In South Asia, firms report almost one outage a day, lasting 5.7 hours on average.

- In South Asia, firms report almost one outage a day, lasting 5.

- 7 hours on average.

**Comment by arun369** [comment]
@ulziibadrakh-p I was exactly looking for this. Thanks for pointing this out. I have spent a few days already on it to figure this out with RegEx etc and I came across this library and seems like it has the same issue.
